# Generated by Django 2.2.1 on 2019-05-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Person')),
                ('genre', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
