# Generated by Django 2.2.1 on 2019-05-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190515_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='starring',
            field=models.ManyToManyField(null=True, related_name='starring', through='movies.PersonMovie', to='movies.Person'),
        ),
    ]
